# Review Konsep Matriks

Pada notebook ini, kita akan membahas konsep dasar matriks yang penting dalam machine learning.

## Apa itu Matriks?

Matriks adalah kumpulan bilangan yang disusun dalam baris dan kolom yang membentuk persegi panjang. Matriks digunakan untuk merepresentasikan data dalam jumlah besar secara terstruktur.

## Notasi Matriks

Matriks biasanya dilambangkan dengan huruf kapital seperti A, B, C, dll. Sebuah matriks dengan m baris dan n kolom disebut sebagai matriks m × n.

$$A = \begin{bmatrix} 
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

## Pentingnya Matriks dalam Machine Learning

Dalam machine learning, matriks digunakan untuk:
- Representasi data (sampel sebagai baris, fitur sebagai kolom)
- Transformasi linear
- Sistem persamaan linear
- Operasi pada data berdimensi tinggi

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Contoh membuat matriks
A = np.array([[1, 2, 3], 
              [4, 5, 6], 
              [7, 8, 9]])

print("Matriks A:")
print(A)
print("\nBentuk matriks A:", A.shape)
print("Dimensi matriks A:", A.ndim)
print("Tipe data matriks A:", A.dtype)

Matriks A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Bentuk matriks A: (3, 3)
Dimensi matriks A: 2
Tipe data matriks A: int64


# Review Konsep Matriks

Matriks adalah kumpulan bilangan, simbol, atau ekspresi yang disusun dalam baris dan kolom membentuk persegi panjang.

## Definisi Matriks

Matriks dengan ukuran $m \times n$ memiliki $m$ baris dan $n$ kolom:

$$A = \begin{bmatrix} 
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}$$

## Jenis-jenis Matriks

1. **Matriks Persegi**: Jumlah baris = jumlah kolom
2. **Matriks Identitas**: Matriks persegi dengan 1 di diagonal utama dan 0 di tempat lain
3. **Matriks Diagonal**: Matriks persegi dengan nilai non-nol hanya pada diagonal utama
4. **Matriks Segitiga Atas**: Matriks dengan elemen di bawah diagonal utama bernilai nol
5. **Matriks Segitiga Bawah**: Matriks dengan elemen di atas diagonal utama bernilai nol
6. **Matriks Simetris**: Matriks yang jika ditranspose hasilnya sama dengan matriks asli

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

# Contoh matriks
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Matriks identitas
I = np.eye(3)

# Tampilkan matriks
print("Matriks A:")
print(A)
print("\nMatriks Identitas 3x3:")
print(I)

# Operasi transpos
print("\nTranspos matriks A:")
print(A.T)

# Review Konsep Matriks

Matriks merupakan kumpulan nilai yang disusun dalam baris dan kolom. Dalam konteks machine learning, matriks sangat penting karena:

1. Data sering direpresentasikan dalam bentuk matriks
2. Transformasi linear pada data direpresentasikan sebagai operasi matriks
3. Banyak algoritma machine learning bergantung pada operasi matriks

## Definisi Matriks

Matriks dengan ukuran m × n adalah array persegi panjang yang terdiri dari m baris dan n kolom. Contoh matriks A dengan ukuran 2 × 3:

$$A = \begin{bmatrix} 
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23}
\end{bmatrix}$$

Di mana $a_{ij}$ adalah elemen pada baris ke-i dan kolom ke-j.

In [1]:
import numpy as np

# Membuat matriks 2x3
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print("Matriks A:")
print(A)
print(f"Dimensi matriks A: {A.shape}")  # Output: (2, 3)

# Membuat matriks dengan nilai 0
B = np.zeros((3, 4))
print("\nMatriks B (zeros):")
print(B)

# Membuat matriks dengan nilai 1
C = np.ones((2, 2))
print("\nMatriks C (ones):")
print(C)

# Membuat matriks identitas 3x3
I = np.eye(3)
print("\nMatriks Identitas 3x3:")
print(I)

Matriks A:
[[1 2 3]
 [4 5 6]]
Dimensi matriks A: (2, 3)

Matriks B (zeros):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Matriks C (ones):
[[1. 1.]
 [1. 1.]]

Matriks Identitas 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Akses Elemen Matriks

Untuk mengakses elemen dalam matriks, kita dapat menggunakan indeks baris dan kolom. Dalam Python dengan NumPy, indeks dimulai dari 0.

In [2]:
# Buat matriks contoh
D = np.array([[10, 20, 30],
              [40, 50, 60],
              [70, 80, 90]])

print("Matriks D:")
print(D)

# Akses elemen pada baris 0, kolom 1 (elemen kedua pada baris pertama)
print("\nD[0, 1] =", D[0, 1])  # Output: 20

# Akses baris pertama
print("\nBaris pertama D[0] =", D[0])

# Akses kolom kedua
print("\nKolom kedua D[:, 1] =", D[:, 1])

# Slicing: ambil submatriks 2x2 dari pojok kiri atas
print("\nSubmatriks 2x2 dari D:")
print(D[0:2, 0:2])

Matriks D:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

D[0, 1] = 20

Baris pertama D[0] = [10 20 30]

Kolom kedua D[:, 1] = [20 50 80]

Submatriks 2x2 dari D:
[[10 20]
 [40 50]]


## Operasi Dasar Matriks

### 1. Penjumlahan dan Pengurangan

Operasi penjumlahan dan pengurangan matriks dilakukan elemen per elemen. Dua matriks harus memiliki dimensi yang sama untuk operasi ini.

In [3]:
# Buat dua matriks dengan dimensi yang sama
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("Matriks A:")
print(A)
print("\nMatriks B:")
print(B)

# Penjumlahan matriks
C = A + B
print("\nA + B =")
print(C)

# Pengurangan matriks
D = A - B
print("\nA - B =")
print(D)

# Perkalian elemen per elemen (Hadamard product)
E = A * B
print("\nA * B (element-wise) =")
print(E)

Matriks A:
[[1 2]
 [3 4]]

Matriks B:
[[5 6]
 [7 8]]

A + B =
[[ 6  8]
 [10 12]]

A - B =
[[-4 -4]
 [-4 -4]]

A * B (element-wise) =
[[ 5 12]
 [21 32]]


### 2. Perkalian Matriks

Perkalian matriks A dan B dapat dilakukan jika jumlah kolom pada A sama dengan jumlah baris pada B. Jika A berukuran m×n dan B berukuran n×p, hasil perkalian A×B akan berukuran m×p.

$$C_{ij} = \sum_{k=1}^{n} A_{ik} \times B_{kj}$$

### 3. Transposisi Matriks

Transposisi matriks mengubah baris menjadi kolom dan sebaliknya. Jika A adalah matriks m×n, maka transpose A (ditulis A^T) adalah matriks n×m.

In [4]:
# Perkalian Matriks
A = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2x3 matrix

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])  # 3x2 matrix

# Perkalian matriks dengan operator @
C = A @ B
# Atau bisa juga dengan: C = np.matmul(A, B)

print("Matriks A (2x3):")
print(A)
print("\nMatriks B (3x2):")
print(B)
print("\nHasil A × B (2x2):")
print(C)

# Transpose matriks
A_transpose = A.T
print("\nMatriks A:")
print(A)
print("\nTranspose dari A (A^T):")
print(A_transpose)

Matriks A (2x3):
[[1 2 3]
 [4 5 6]]

Matriks B (3x2):
[[ 7  8]
 [ 9 10]
 [11 12]]

Hasil A × B (2x2):
[[ 58  64]
 [139 154]]

Matriks A:
[[1 2 3]
 [4 5 6]]

Transpose dari A (A^T):
[[1 4]
 [2 5]
 [3 6]]


## Jenis-jenis Matriks Khusus

### 1. Matriks Identitas (Identity Matrix)
Matriks persegi dengan nilai 1 pada diagonal utama dan 0 di tempat lain. Dilambangkan dengan I.

### 2. Matriks Diagonal
Matriks persegi dengan nilai non-zero hanya pada diagonal utama.

### 3. Matriks Segitiga Atas (Upper Triangular)
Matriks persegi dengan nilai 0 di bawah diagonal utama.

### 4. Matriks Segitiga Bawah (Lower Triangular)
Matriks persegi dengan nilai 0 di atas diagonal utama.

### 5. Matriks Simetris
Matriks A di mana A = A^T.

### 6. Matriks Singular dan Non-singular
Matriks persegi adalah singular jika determinannya 0, dan non-singular jika determinannya tidak 0.

In [5]:
# Matriks identitas
I = np.eye(3)
print("Matriks Identitas 3x3:")
print(I)

# Matriks diagonal
D = np.diag([1, 2, 3])
print("\nMatriks Diagonal:")
print(D)

# Matriks segitiga atas
U = np.array([[1, 2, 3],
              [0, 4, 5],
              [0, 0, 6]])
print("\nMatriks Segitiga Atas:")
print(U)

# Matriks segitiga bawah
L = np.array([[1, 0, 0],
              [2, 3, 0],
              [4, 5, 6]])
print("\nMatriks Segitiga Bawah:")
print(L)

# Matriks simetris
S = np.array([[1, 2, 3],
              [2, 4, 5],
              [3, 5, 6]])
print("\nMatriks Simetris:")
print(S)
print("S == S.T :", np.array_equal(S, S.T))

# Matriks singular dan non-singular
A = np.array([[1, 2], 
              [2, 4]])  # Singular (determinan = 0)
print("\nMatriks A (singular):")
print(A)
print("Determinan A:", np.linalg.det(A))

B = np.array([[1, 2], 
              [3, 4]])  # Non-singular
print("\nMatriks B (non-singular):")
print(B)
print("Determinan B:", np.linalg.det(B))

Matriks Identitas 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriks Diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Matriks Segitiga Atas:
[[1 2 3]
 [0 4 5]
 [0 0 6]]

Matriks Segitiga Bawah:
[[1 0 0]
 [2 3 0]
 [4 5 6]]

Matriks Simetris:
[[1 2 3]
 [2 4 5]
 [3 5 6]]
S == S.T : True

Matriks A (singular):
[[1 2]
 [2 4]]
Determinan A: 0.0

Matriks B (non-singular):
[[1 2]
 [3 4]]
Determinan B: -2.0000000000000004


## Pentingnya Matriks dalam Machine Learning

Dalam machine learning, matriks memiliki peran yang sangat penting:

1. **Representasi Data**: Data dalam machine learning sering direpresentasikan sebagai matriks, di mana setiap baris adalah sampel dan setiap kolom adalah fitur.

2. **Transformasi Linear**: Banyak operasi dalam machine learning (seperti PCA, SVD) melibatkan transformasi linear yang direpresentasikan sebagai operasi matriks.

3. **Neural Networks**: Operasi dalam jaringan saraf melibatkan perkalian matriks bobot dengan input.

4. **Sistem Persamaan Linear**: Banyak masalah optimasi dalam machine learning melibatkan penyelesaian sistem persamaan linear.

5. **Metrik Jarak dan Kemiripan**: Perhitungan jarak dan kemiripan antara data sering melibatkan operasi matriks.

Mari kita lihat contoh sederhana penggunaan matriks dalam konteks data machine learning:

In [6]:
# Contoh representasi dataset sebagai matriks
# Dataset: 4 sampel dengan 3 fitur (misalnya tinggi, berat, dan usia)
X = np.array([
    [170, 65, 25],  # Sampel 1: tinggi 170cm, berat 65kg, usia 25 tahun
    [160, 55, 30],  # Sampel 2
    [180, 75, 35],  # Sampel 3
    [165, 60, 28]   # Sampel 4
])

print("Dataset X (4 sampel × 3 fitur):")
print(X)
print(f"Dimensi: {X.shape}")

# Menghitung mean untuk setiap fitur
mean_features = X.mean(axis=0)
print("\nRata-rata setiap fitur:")
print(mean_features)

# Menormalisasi data (standardisasi)
# (X - mean) / std
X_normalized = (X - X.mean(axis=0)) / X.std(axis=0)
print("\nDataset ternormalisasi:")
print(X_normalized)
print("Mean dari data ternormalisasi:", X_normalized.mean(axis=0))
print("Std dari data ternormalisasi:", X_normalized.std(axis=0))

# Contoh transformasi linear: proyeksi ke dimensi yang lebih rendah
# Misalnya kita ingin memetakan data 3 fitur ke ruang 2 dimensi
projection_matrix = np.array([
    [0.8, 0.2],     # Koefisien untuk fitur 1
    [0.7, 0.3],     # Koefisien untuk fitur 2
    [0.6, 0.4]      # Koefisien untuk fitur 3
])

# Lakukan proyeksi: X_projected = X × projection_matrix
X_projected = X @ projection_matrix
print("\nDataset setelah proyeksi ke 2 dimensi:")
print(X_projected)
print(f"Dimensi baru: {X_projected.shape}")  # Sekarang 4 sampel × 2 fitur

Dataset X (4 sampel × 3 fitur):
[[170  65  25]
 [160  55  30]
 [180  75  35]
 [165  60  28]]
Dimensi: (4, 3)

Rata-rata setiap fitur:
[168.75  63.75  29.5 ]

Dataset ternormalisasi:
[[ 0.16903085  0.16903085 -1.23624508]
 [-1.18321596 -1.18321596  0.13736056]
 [ 1.52127766  1.52127766  1.5109662 ]
 [-0.50709255 -0.50709255 -0.41208169]]
Mean dari data ternormalisasi: [ 0.00000000e+00  0.00000000e+00 -1.38777878e-17]
Std dari data ternormalisasi: [1. 1. 1.]

Dataset setelah proyeksi ke 2 dimensi:
[[196.5  63.5]
 [184.5  60.5]
 [217.5  72.5]
 [190.8  62.2]]
Dimensi baru: (4, 2)


## Kesimpulan

Dalam notebook ini, kita telah mempelajari:
- Definisi dasar matriks
- Cara membuat dan mengakses elemen matriks menggunakan NumPy
- Operasi dasar matriks: penjumlahan, pengurangan, perkalian, dan transposisi
- Jenis-jenis matriks khusus
- Pentingnya matriks dalam konteks machine learning

Matriks adalah fondasi matematika yang sangat penting untuk memahami algoritma machine learning. Banyak algoritma dan teknik machine learning didasarkan pada operasi dan properti matriks yang telah kita bahas.

## Latihan

1. Buat matriks 3×3 yang merupakan matriks simetris.
2. Hitung hasil dari perkalian matriks berikut:
   $$\begin{bmatrix} 1 & 0 & 2 \\ -1 & 3 & 1 \end{bmatrix} \times \begin{bmatrix} 3 & 1 \\ 2 & 1 \\ 1 & 0 \end{bmatrix}$$
3. Buatlah sebuah dataset dummy dengan 5 sampel dan 4 fitur, kemudian normalisasi dataset tersebut.

In [7]:
# Latihan 1: Membuat matriks simetris 3×3
sym_matrix = np.array([
    [5, 2, 3],
    [2, 4, 1],
    [3, 1, 6]
])

print("Matriks Simetris:")
print(sym_matrix)
print("Verifikasi simetris (sym_matrix == sym_matrix.T):", np.array_equal(sym_matrix, sym_matrix.T))

# Latihan 2: Perkalian matriks
A = np.array([
    [1, 0, 2],
    [-1, 3, 1]
])

B = np.array([
    [3, 1],
    [2, 1],
    [1, 0]
])

result = A @ B
print("\nHasil perkalian matriks A × B:")
print(result)

# Latihan 3: Dataset dummy dan normalisasi
# Buat dataset dengan 5 sampel dan 4 fitur
dummy_data = np.array([
    [10, 20, 30, 40],  # Sampel 1
    [15, 25, 35, 45],  # Sampel 2
    [20, 30, 40, 50],  # Sampel 3
    [25, 35, 45, 55],  # Sampel 4
    [30, 40, 50, 60]   # Sampel 5
])

print("\nDataset dummy:")
print(dummy_data)

# Normalisasi: (X - mean) / std
dummy_norm = (dummy_data - dummy_data.mean(axis=0)) / dummy_data.std(axis=0)

print("\nDataset ternormalisasi:")
print(dummy_norm)
print("Mean dataset ternormalisasi:", dummy_norm.mean(axis=0))
print("Std dataset ternormalisasi:", dummy_norm.std(axis=0))

Matriks Simetris:
[[5 2 3]
 [2 4 1]
 [3 1 6]]
Verifikasi simetris (sym_matrix == sym_matrix.T): True

Hasil perkalian matriks A × B:
[[5 1]
 [4 2]]

Dataset dummy:
[[10 20 30 40]
 [15 25 35 45]
 [20 30 40 50]
 [25 35 45 55]
 [30 40 50 60]]

Dataset ternormalisasi:
[[-1.41421356 -1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356  1.41421356]]
Mean dataset ternormalisasi: [0. 0. 0. 0.]
Std dataset ternormalisasi: [1. 1. 1. 1.]
